language: go

go:
  - 1.11

branches:
  only:
    - master

env:
  global:
    - ROOT=$SHIPPABLE_BUILD_DIR/src

build:
  ci:
    - cd $ROOT
    - go run main.go

jobs:
  - name: shippable_test
    type: runCI
    steps:
      - OUT: shippable_test