language: go

go:
  - 1.11

branches:
  only:
    - master

env:
  global:
    - DOCKER_ACC=punchh
    - DOCKER_REPO=shippable-cdp

build:
  ci:
    - cd ..
    - mkdir src
    - mv cdp src
    - apt-get install golang
    - export GOPATH=$(pwd) GOBIN=$(pwd)
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - cd src/cdp
  post_ci:
    - go run main.go

jobs:
  - name: shippable-test
    type: runCI
    steps:
      - OUT: shippable-test